// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi.Models;

public partial class Factura
{
    public int IdFactura { get; set; }

    public string Serie { get; set; }

    public string Folio { get; set; }

    public int? IdEstadoDocumento { get; set; }

    public decimal? Subtotal { get; set; }

    public decimal? TotalDescuento { get; set; }

    public int IdCliente { get; set; }

    public decimal? TotalImpuestos { get; set; }

    public decimal? Total { get; set; }

    public int IdFormaPago { get; set; }

    public int IdMetodoPago { get; set; }

    public int IdMoneda { get; set; }

    public DateTime? FechaEmision { get; set; }

    public virtual ICollection<FacturaDetalle> FacturaDetalles { get; set; } = new List<FacturaDetalle>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual EstadoDocumento IdEstadoDocumentoNavigation { get; set; }

    public virtual FormaPago IdFormaPagoNavigation { get; set; }

    public virtual MetodoPago IdMetodoPagoNavigation { get; set; }

    public virtual Monedum IdMonedaNavigation { get; set; }
}